#!/usr/bin/env python3
"""Simple 3D models for the parts KiCad's bundled library has none for.

These are honest stand-ins, not vendor CAD: a box the size of the real body,
plus a barrel for the BNCs.  They exist so the 3D render shows the board as it
will actually look, and so a mechanical check against an enclosure has
something to measure.

Written in VRML.  KiCad's convention is 1 model unit = 2.54 mm, so the
footprint entries carry a scale of 1/2.54 and the geometry here is plain
millimetres.  In the model frame X is board +X, Y is board -Y and Z is up out
of the board.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.abspath(os.path.join(HERE, "..", "hardware", "lib",
                                   "lorenz.3dshapes"))
MM = 1.0 / 2.54          # the scale the footprint must apply

HEAD = "#VRML V2.0 utf8\n# Generated by scripts/gen_models.py -- a plain stand-in body.\n"


def material(r, g, b, shininess=0.3):
    return (f"appearance Appearance {{ material Material {{ "
            f"diffuseColor {r} {g} {b} specularColor 0.2 0.2 0.2 "
            f"shininess {shininess} }} }}")


def box(cx, cy, cz, sx, sy, sz, colour):
    return (f"Transform {{ translation {cx:.4f} {cy:.4f} {cz:.4f} children [\n"
            f"  Shape {{ {material(*colour)}\n"
            f"    geometry Box {{ size {sx:.4f} {sy:.4f} {sz:.4f} }} }} ] }}\n")


def prism_x(x0, x1, cy, cz, radius, colour, sides=16):
    """A prism lying along the board's X axis, written as explicit faces.

    KiCad's VRML reader does not draw the `Cylinder` primitive -- an earlier
    version of this file used one and the barrels came out as blocks -- so the
    geometry is spelled out.
    """
    import math
    pts = []
    for x in (x0, x1):
        for i in range(sides):
            a = 2 * math.pi * i / sides
            pts.append((x, cy + radius * math.cos(a), cz + radius * math.sin(a)))
    coords = ", ".join(f"{p[0]:.4f} {p[1]:.4f} {p[2]:.4f}" for p in pts)
    faces = []
    for i in range(sides):
        j = (i + 1) % sides
        faces.append(f"{i} {j} {j + sides} {i + sides} -1")
    faces.append(" ".join(str(i) for i in range(sides)) + " -1")
    faces.append(" ".join(str(i + sides) for i in reversed(range(sides))) + " -1")
    return ("Shape {\n  " + material(*colour) + "\n"
            "  geometry IndexedFaceSet {\n"
            "    creaseAngle 1.0 solid TRUE\n"
            f"    coord Coordinate {{ point [ {coords} ] }}\n"
            f"    coordIndex [ {' '.join(faces)} ]\n"
            "  } }\n")


SILVER = (0.52, 0.54, 0.57)
BLACK = (0.12, 0.12, 0.13)
WHITE = (0.88, 0.88, 0.86)
CREAM = (0.85, 0.80, 0.62)


def bnc():
    """Body 10 x 10 x 12.2 mm on the board, barrel on +X, axis 6.1 mm up."""
    s = HEAD
    s += box(0, 0, 6.1, 10.0, 10.0, 12.2, SILVER)
    s += prism_x(5.0, 19.5, 0, 6.1, 4.8, SILVER)          # threaded barrel
    s += prism_x(19.5, 23.0, 0, 6.1, 6.0, SILVER, sides=6)  # coupling nut
    s += prism_x(23.0, 24.5, 0, 6.1, 4.0, SILVER)          # front lip
    s += prism_x(6.0, 24.5, 0, 6.1, 0.6, (0.85, 0.7, 0.3))  # centre contact
    return "BNC_KYWE_RightAngle.wrl", s


def dcdc():
    """19.65 x 7.0 x 10.16 mm brick, pin 1 at the footprint origin."""
    s = HEAD
    # footprint: pins on a 2.54 grid from x=0, body -2.21..17.44 in x and
    # -6.1..0.9 in board y, which is +6.1..-0.9 in the model frame
    s += box(7.615, 2.6, 5.08, 19.65, 7.0, 10.16, BLACK)
    return "DCDC_SIP_A05xxS.wrl", s


def usbc():
    """The HRO receptacle's steel shell, opening toward the board edge."""
    s = HEAD
    s += box(0, -0.6, 1.63, 8.94, 7.35, 3.26, SILVER)
    return "USB_C_HRO_TYPE-C-31-M-12.wrl", s


def dipswitch():
    """KingTek DSIC06LSGET: 15.24 x 6.00 mm body, 1.8 mm tall, six sliders.

    Drawn here rather than borrowed from KiCad's bundled 3D set, which is a
    reduced selection in the AppImage and may not have it.
    """
    s = HEAD
    s += box(0, 0, 1.15, 6.00, 15.24, 1.80, BLACK)
    # the six actuators, pushed to the "ON" side
    for i in range(6):
        y = -6.35 + i * 2.54
        s += box(-1.1, y, 2.15, 1.30, 1.10, 0.70, WHITE)
    s += box(2.55, 0, 1.15, 0.30, 15.24, 1.60, (0.55, 0.55, 0.55))
    return "SW_DIP_x06_DSIC06.wrl", s


def led_rgb():
    """MEIHUA MHPC3528CRGBCT: 3.5 x 2.8 mm PLCC-4, 1.85 mm tall.

    A white body with a clear dome, so the render shows the lamp rather than
    another black rectangle.
    """
    s = HEAD
    s += box(0, 0, 0.42, 3.5, 2.8, 0.84, WHITE)         # the PLCC cup
    s += box(0, 0, 1.35, 3.1, 2.4, 1.02, (0.80, 0.82, 0.84))   # clear lens
    s += box(0, 0, 0.30, 2.0, 1.4, 0.10, (0.35, 0.35, 0.38))   # the dies
    return "LED_RGB_PLCC4.wrl", s


def fuse1812():
    s = HEAD
    s += box(0, 0, 0.55, 4.5, 3.2, 1.1, CREAM)
    return "Fuse_1812.wrl", s


def main():
    os.makedirs(OUT, exist_ok=True)
    for maker in (bnc, dcdc, usbc, fuse1812, dipswitch, led_rgb):
        name, body = maker()
        with open(os.path.join(OUT, name), "w") as fh:
            fh.write(body)
        print(f"  wrote {os.path.relpath(os.path.join(OUT, name))}")


if __name__ == "__main__":
    main()
